### ISSUE TITLE
raise child_exception

### ISSUE THREAD

**Issue by cubiczx** [e-shulitsky/adeezer#8]
``` python
adeezer-master cubiczx$ python adeezer.py -p 1306275535
Tracks to download:
Joey Montana - Love & Party (from WWW.DEEZER.LINK).mp3
Pilson - Calor De Verano (from WWW.DEEZER.LINK).mp3
Danny Romero - Motívate (from WWW.DEEZER.LINK).mp3
Dasoul - De Lao a Lao (from WWW.DEEZER.LINK).mp3
Daddy Yankee - Limbo (from WWW.DEEZER.LINK).mp3
Nitro & La Melodia - Tukutaka (Single) (from WWW.DEEZER.LINK).mp3
Crazy Design - El Teke Teke (from WWW.DEEZER.LINK).mp3
Miguel Saez - La Cazadora (from WWW.DEEZER.LINK).mp3
Carlos Vives - Volví a Nacer (Urban Version) (from WWW.DEEZER.LINK).mp3
Victor Magan - Besame en la Boca (from WWW.DEEZER.LINK).mp3
Rodriguez - No Voy a Llorar (feat. Ander & Rossi) (Radio Edit) (from WWW.DEEZER.LINK).mp3
Danny Romero - Bandida (from WWW.DEEZER.LINK).mp3
Danny Romero - 18 Años (from WWW.DEEZER.LINK).mp3
Danny Romero - Agachate (Original Mix) (from WWW.DEEZER.LINK).mp3
Dasoul - Él No Te Da (from WWW.DEEZER.LINK).mp3
Danny Romero - Carnaval (Venimos a Celebrar) (from WWW.DEEZER.LINK).mp3
Daddy Yankee - Sígueme Y Te Sigo (from WWW.DEEZER.LINK).mp3
Keymass & Bonche - Pequeña Sambea (from WWW.DEEZER.LINK).mp3
Keymass & Bonche - Para Que Baile Dembow (from WWW.DEEZER.LINK).mp3
Ilegales - Chucuchá (from WWW.DEEZER.LINK).mp3
Traceback (most recent call last):
  File "adeezer.py", line 123, in <module>
    xvfb.start()
  File "/Library/Python/2.7/site-packages/xvfbwrapper.py", line 53, in start
    stderr=open(os.devnull),
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 709, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1326, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by cubiczx** [comment]
I imagine that as it is now does not work payment
